//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayforcars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid
    {
        public string User_ID { get; set; }
        public int Bid_ID { get; set; }
        public string Amount { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> product_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
